config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  root 'dashboards#landing'

  resources :tree_badges
  resources :forests do
    resources :trees do
    end
  end

  resources :trees

  resources :dashboards do
    collection do
      get :forest_types
    end
  end

end

app/models/forest.rb
class Forest < ActiveRecord::Base
	has_many :trees
	belongs_to :forest_badge
end

app/models/forest_badge.rb
class ForestBadge < ActiveRecord::Base
  belongs_to :user
  belongs_to :forest
end

app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :user
	belongs_to :tree
end

app/models/tree.rb
class Tree < ActiveRecord::Base
	belongs_to :forest
	belongs_to :tree_badge
	has_many :images
end

app/models/tree_badge.rb
class TreeBadge < ActiveRecord::Base
  belongs_to :user
  belongs_to :tree
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :forest_badges
  has_many :forests, through: :forest_badges
  has_many :tree_badges
  has_many :trees, through: :tree_badges
  has_many :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception



end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  Result = Struct.new(:forest_type, :radius) do
    def forest_type_name
      ForestTypesHelper::FOREST_TYPES[forest_type]
    end
  end

  def landing
    @disable_nav = true
    if current_user
      redirect_to dashboards_path
    else
      render action: "landing"
    end
  end

	def index
		@user = current_user
		@forests = Forest.all
    @results = []
    render action: "index"
	end

  def forest_types
    @forests = Forest.all
    @results = get_forest_types(params[:x], params[:y], params[:radius])
    render action: "search"
  end

  private

  def get_forest_types(x,y,radius)
    x = 174.75878033265786 if x.nil? || x.empty?
    y = -41.29443668919478 if y.nil? || y.empty?
    radius = 10 if radius.nil? || radius.empty?
    raw_json = HTTParty.get "http://api.lris.scinfo.org.nz/api/vectorQuery.json?key=3479c35b1848488e88fa424047c58641&layer=423&x=#{x}&y=#{y}&max_results=10&radius=#{radius}"
    parsed_json = JSON.parse(raw_json)

    raw_results = parsed_json["vectorQuery"]["layers"]["423"]["features"]
    results_to_return = []

    raw_results.each do |result|
      forest_type = result["properties"]["Class_2012"]
      if ForestTypesHelper::FOREST_TYPES.include?(result["properties"]["Class_2012"])
        results_to_return << Result.new(forest_type, result["distance"])
      end
    end
    return results_to_return
  end
end

app/controllers/forests_controller.rb
class ForestsController < ApplicationController
	def show
		@user = current_user
		@forest = Forest.find(params[:id])
		@trees = @forest.trees
		@badges = TreeBadge.where(user_id: @user.id)
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    '/dashboards'
  end
end

app/controllers/tree_badges_controller.rb
class TreeBadgesController < ApplicationController
  def index
    @user = current_user
    all_user_badges = TreeBadge.where(user_id: current_user.id)
    # variable names:
   @badge_names =  ForestTypesHelper::FOREST_TYPES.values.collect {|name| "@" + name.downcase.tr(" ", "_") + "_badges"}

    # @badge_names =  ["@fernland_badges", "@manuka_badges", "@podocarp_giants_badges", "@mangrove_badges", "@deciduous_hardwood_badges", "@nothofagus_beech_badges", "@exotic_badges"]
    ForestTypesHelper::FOREST_TYPES.each do |key,value|
      forest_tree_ids = Forest.find_by(name: value).trees.pluck(:id)#[1,2,3,4,5]
      name = value.downcase.tr(" ", "_")# podocarp_giant
      query = all_user_badges.where(tree_id: forest_tree_ids)
      instance_variable_set("@#{name}_badges", query) #@podocarp_giant_badges
    end
  end

  def new
  	@badge = TreeBadge.new
  end

  def create
    # TODO: update images to be stored in image table
    @user = current_user
    @badge =TreeBadge.create({user_id: @user.id}.merge(badge_params))
    respond_to do |format|
      format.js {render inline: "location.reload();" }
    end
  end

  private
  def badge_params
    params.require(:tree_badge).permit(:tree_id, :image)
  end
end

app/controllers/trees_controller.rb
class TreesController < ApplicationController
	def index
		@forest = Forest.find(params[:forest_id])
		@trees = @forest.trees
	end

  def show
    @tree = Tree.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = current_user
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forest_types_helper.rb
module ForestTypesHelper
FOREST_TYPES = {
    50 =>'Fernland',
    52 =>'Manuka',
    54 => 'Podocarp Giant',
    70 => 'Mangrove',
    68 => 'Deciduous Hardwood',
    69 => 'Nothofagus Beech',
    71 => 'Exotic'
  }

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/application/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Tree Hugger</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

      </ul>
       <ul class="nav navbar-nav navbar-right">

        <% if user_signed_in?%>
          <li><a href="/tree_badges">Badges <span class="badge"><%= current_user.trees.count%></span></a></li>
          <li><%= link_to current_user.email, edit_user_registration_path %></li>
          <li><%= link_to "logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/dashboards/index.html.erb
<% if user_signed_in?%>



<div id= "jumbo-description" class="jumbotron text-center">
  <!-- <h1 id="jumbo-header-text thirty-px-left">Hug </br>  Trees </br> Today</h1> -->
  <h1> Connect to nature - <span class="logo-font text-success">Literally</span>.</h1>
 <p>Give our trees the love they deserve and get to know our native species a little better</p>
</div>

<div id= "jumbo-steps" class="jumbotron text-center">
  <!-- <h1 id="jumbo-header-text thirty-px-left">Hug </br>  Trees </br> Today</h1> -->
 <p>Choose your forest type</p>
<%= fa_icon "tree", class: "fa-4x" %>
<p>Earn a badge by uploading a pic appreciating each tree</p>
<%= fa_icon "camera-retro", class: "fa-4x" %>
<p>Collect all the badges</p>
<%= inline_svg("badge.svg",  class: 'tree-badge-svg-alone') %>
<p>Win prizes!</p>
<%= fa_icon "trophy", class: "fa-4x" %>
</br>
 <a class="btn btn-success btn-lg ten-top-margin" href= <%= forest_types_dashboards_path %> role="button">Find Forests Now</a>
</div>



<% end %>

app/views/dashboards/landing.html.erb
<div class="row">
	<div class="pull-right login-links">
	<%= link_to "Log In", new_user_session_path, class: "text-success user-links"%>
	<%= link_to "Sign Up", new_user_registration_path, class: "text-success user-links" %>
	</div>
</div>
<div class="forest-wrapper landing">
	<div class="row">
		<div class="col-md 6 text-center">
			<h1 class="text-success treehugger">TreeHugger</h1>
			<h2>Get to know New Zealand's native species a little better.</h2>
			<img class="landing-logo" src="http://i.imgur.com/hHODVVY.png" alt="Tree Hugger Logo"/>
		</div>
	</div>
</div>	

app/views/dashboards/search.html.erb
<div class="forest-wrapper">
	<h2>Enter a location and a search radius</h2>
	<div id "jumbo-form" class="search-form">
	<a name="finder-form"></a>
	<%= form_tag('/dashboards/forest_types', method: "get") do %>
	    <%= text_field_tag('y', nil, { placeholder: "Latitude (deg)" } ) %>
	    <%= text_field_tag('x', nil,  { placeholder: "Longitude (deg)" } ) %>
	    <%= text_field_tag('radius', nil, {placeholder: "radius (km)" }) %>
	    <%= submit_tag("Search", class: "btn btn-success") %>
	<% end %>
	<p>Please enter a radius in kilometres to search for forests in your area. example: '50' or '1000'</p>
	<p>Coordinates will default to Zealandia if no latitude and longitude are entered. Zealandia: (-41.29443668919478, 174.75878033265786). </p>
	</div>

<% if @results.any? %>
<h2>Forests in your Area</h2>
<% end %>
<% @results.each do |result| %>
<!-- forest name links to forest type show page -->
<% forest = Forest.find_by(name: result.forest_type_name) %>
<p><%= link_to(result.forest_type_name, forest_path(forest)) %>
<%= "species within a radius of #{result.radius} meters"%></p>
<% end %>
</div>

app/views/forests/show.html.erb
<div class="forest-wrapper">


<% if @badges.count == 5 %>
  <div id="badge-success" class="row">
    <h3>You have <span class="logo-font text-success">Hugged</span> all the trees!</h3>
  </div>
<%  end  %>


  <h2><%= @forest.name %></h2>
  <p><%= @forest.description %></p>
  <div id="forest-tree" class="row">
    <%= render @trees %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TreeHugger</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "navbar" unless @disable_nav %>
  <% if !flash[:notice].blank? %>
    <div class="alert alert-info"><%= notice %></div>
  <% elsif !flash[:alert].blank? %>
    <div class="alert alert-warning"><%= alert %></div>
  <% end %>
  <%= yield %>

</body>
<footer></footer>
</html>

app/views/tree_badges/_new.html.erb
<%= form_for(badge, url: tree_badges_path(), remote: true) do |f| %>
  <div class="field">
    <%= f.hidden_field 'tree_id', :value => tree.id %>
    <%= f.label "post_your_hug-shot" %><br />
    <%= f.url_field :image, :placeholder => "URL to photo" %>
  </div>
  <div class="actions">
    <%= f.submit "Collect Badge", class: "btn btn-success" %>
  </div>
<% end %>

app/views/tree_badges/index.html.erb
<div class="forest-wrapper">
  <h1> Tree Lovin' </h1>
  <!-- loop through forest type names -->
  <!-- display your count of badges againgst total trees in forst count -->
  <% @badge_names.each do |badge_name| %>


  <%forest_name = badge_name.gsub(/_/, ' ').gsub("badges","").gsub("@","").split.map(&:capitalize).join(' ') %>
  <% forest = Forest.find_by(name: forest_name) %>

  <p><%= "you've embraced #{instance_variable_get(badge_name).count} out of 10 trees from the"%>
      <%= link_to(forest_name, forest_path(forest)) %>
      forest
  </p>
  <% end %>
</div>

app/views/trees/_tree.html.erb
<% if !TreeBadge.where(tree_id: tree.id, user_id: @user.id).any? %>
	<div>
		<div class="tree-tile">
			<%= link_to image_tag(tree.images.first.source), tree_path(tree.id), target: "_blank" %>
		</div>
		<h3 class="text-center text-tile"><%=link_to tree.name, tree_path(tree.id), target: "_blank" %></h3>
		<div class="text-center collect-badge <%= tree.id %>">
			<%= render partial: 'tree_badges/new', locals: {badge: TreeBadge.new, tree: tree, user: @user} %>
		</div>
	</div>
<% else %>
	<div>
		<div class="tree-tile">
		<!-- TODO: reference images to be stored in image table -->
			<img src="<%=  @badges.find_by(tree_id: tree.id).image %>" alt="">
		</div>
			<h3 class="text-center text-tile"><%=link_to tree.name, tree_path(tree.id), target: "_blank"%></h3>
			<div class="text-center">
				<%= inline_svg("badge.svg",  class: 'tree-badge-svg') %>
			</div>
			<div class="text-center">
				<span class="badge-text text-success">Hugg'd</span>
			</div>
	</div>
<% end %>

app/views/trees/index.js.erb
$("#tree-items-<%= @forest.id%>").html("<%= j render( @trees, locals: {forest: @forest}, remote: true ) %>")

app/views/trees/show.html.erb
<div class="forest-wrapper">
	<h2> <%= "#{@tree.name}" %> </h2>
	<h3>  part of the
	<%= link_to(@tree.forest.name, forest_path(@tree.forest)) %>
	forest
	</h3>
	<div class="row">
		<% @tree.images.each do |image| %>
			<div class="tree-tile">
				<%= image_tag image.source %>
			</div>
		<% end %>
	</div>
	<div class="row tree-description">
		<div class="col-md-8"><%= @tree.description %></div>
	</div>
</div>

app/views/users/show.html.erb
<div> user show</div>